# upload_to_drive.py
import os
import pickle
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# ==============================================
# CONFIGURATION
# ==============================================
CLIENT_SECRET_FILE = 'client_secret.json'   # will be created from secret
TOKEN_PICKLE       = 'token.pickle'         # will be created from secret
SCOPES = ['https://www.googleapis.com/auth/drive.file']

FILE_TO_UPLOAD     = 'plot.png'             # generated by the plot step
UPLOAD_MIME_TYPE   = 'image/png'

TARGET_FOLDER_NAME = 'My Python Uploads'
PARENT_FOLDER_ID   = "1gvq6_ORwy_NUl84TwJApREVtgYoTMn-g"   # optional

# ==============================================
def get_drive_service():
    creds = None
    if os.path.exists(TOKEN_PICKLE):
        with open(TOKEN_PICKLE, 'rb') as f:
            creds = pickle.load(f)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            raise RuntimeError("No valid credentials – refresh token missing or revoked")

        # Save refreshed token back (optional in CI, but safe)
        with open(TOKEN_PICKLE, 'wb') as f:
            pickle.dump(creds, f)

    return build('drive', 'v3', credentials=creds)

# ==============================================
def get_or_create_folder(service, folder_name, parent_id=None):
    query = f"name='{folder_name}' and mimeType='application/vnd.google-apps.folder' and trashed=false"
    if parent_id:
        query += f" and '{parent_id}' in parents"

    resp = service.files().list(q=query, spaces='drive', fields='files(id, name)').execute()
    folders = resp.get('files', [])
    if folders:
        return folders[0]['id']

    metadata = {'name': folder_name, 'mimeType': 'application/vnd.google-apps.folder'}
    if parent_id:
        metadata['parents'] = [parent_id]

    folder = service.files().create(body=metadata, fields='id').execute()
    print(f"Created folder '{folder_name}' (ID: {folder.get('id')})")
    return folder.get('id')

# ==============================================
def upload_file(service, file_path, mime_type, folder_id):
    file_name = os.path.basename(file_path)
    media = MediaFileUpload(file_path, mimetype=mime_type, resumable=True)
    metadata = {'name': file_name, 'parents': [folder_id]}

    file = service.files().create(body=metadata, media_body=media,
                                  fields='id, name, webViewLink').execute()
    print(f"Uploaded: {file.get('name')} – {file.get('webViewLink')}")
    return file.get('id')

# ==============================================
def main():
    if not os.path.exists(FILE_TO_UPLOAD):
        raise FileNotFoundError(f"{FILE_TO_UPLOAD} not found!")
    service = get_drive_service()
    folder_id = get_or_create_folder(service, TARGET_FOLDER_NAME, PARENT_FOLDER_ID)
    upload_file(service, FILE_TO_UPLOAD, UPLOAD_MIME_TYPE, folder_id)

if __name__ == '__main__':
    main()
